// Mapping from Google Sheets column names (with spaces) to camelCase field names (for UI)
export const workerKeyMapping: Record<string, string> = {
  'Worker ID': 'workerId',
  'Onboarding Date': 'onboardingDate',
  'Full Name': 'fullName',
  'Gender': 'gender',
  'DOB': 'dob',
  'Age': 'age',
  'Religion': 'religion',
  "Mother's Name": 'mothersName',
  "Father's Name": 'fathersName',
  "Husband's Name": 'husbandsName',
  'Marital Status': 'maritalStatus',
  'Education': 'education',
  'Mobile': 'mobile',
  'WhatsApp': 'whatsapp',
  'Email': 'email',
  'Present Address': 'presentAddress',
  'Permanent Address': 'permanentAddress',
  'Location': 'location',
  'Reference 1': 'reference1',
  'Reference 1 Relation': 'reference1Relation',
  'Reference 2': 'reference2',
  'Reference 2 Relation': 'reference2Relation',
  'Emergency 1': 'emergency1',
  'Emergency 1 Relation': 'emergency1Relation',
  'Emergency 2': 'emergency2',
  'Emergency 2 Relation': 'emergency2Relation',
  'Known Language\n(Hindi) READ': 'hindiRead',
  'Known Language\n(Hindi) WRITE': 'hindiWrite',
  'Known Language\n(Hindi) SPEAK': 'hindiSpeak',
  'Known Language\n(Eng) READ': 'englishRead',
  'Known Language\n(Eng) WRITE': 'englishWrite',
  'Known Language\n(Eng) SPEAK': 'englishSpeak',
  'Past Experience': 'pastExperience',
  'Previous Employer 1': 'previousEmployer1',
  'Previous Employer 2': 'previousEmployer2',
  'Previous Employer Remarks': 'previousEmployerRemarks',
  'Health Conditions': 'healthConditions',
  'Joining Source': 'joiningSource',
  'Source Details': 'sourceDetails',
  'Bank Account Holder Name': 'bankAccountHolderName',
  'Bank Name': 'bankName',
  'Branch Name': 'branchName',
  'Bank Account Number': 'bankAccountNumber',
  'IFSC': 'ifsc',
  'UPI ID': 'upiId',
  'Worker Photo': 'workerPhoto',
  'Aadhaar Number': 'aadhaarNumber',
  'Aadhaar Front Link': 'aadhaarFront',
  'Aadhaar Back Link': 'aadhaarBack',
  'Voter ID Number': 'voterIdNumber',
  'Voter ID Front Link': 'voterIdFront',
  'Voter ID Back Link': 'voterIdBack',
  'PAN Number': 'panNumber',
  'PAN Card Link': 'panCard',
  'Parent / Husband Aadhar Number': 'parentAadhaarNumber',
  'Parent / Husband Aadhar Front': 'parentAadhaarFront',
  'Parent / Husband Aadhar Back': 'parentAadhaarBack',
  'Police Verification Certificate Link': 'policeVerification',
  'Remarks': 'remarks',
  'Status\n(Active / Inactive / Blacklisted)': 'status',
  'Locality': 'locality',
  'City': 'city',
  'Cooking Services': 'cookingServices',
  'Cleaning Services': 'cleaningServices',
  'BabyCare Services': 'babyCareServices',
  'Elder Care Services': 'elderCareServices',
  'Other Services': 'otherServices',
  'Preferred Work Area': 'preferredWorkArea',
  'Working Status': 'workingStatus',
  'Wiling to Work': 'willingToWork',
  'Availablity In Morning': 'availabilityMorning',
  'Availablity In Noon': 'availabilityNoon',
  'Availablity In Evening': 'availabilityEvening',
  'Full Time Shift\n(8-10 Hours)': 'fullTimeShift',
  'Part Time Shift\n(4-5 Hours)': 'partTimeShift',
  'Live IN Shift\n(24/7 Stay)': 'liveInShift',
  'Daily Shift\n(Daily Basis)': 'dailyShift',
  'Document Status': 'documentStatus',
  'Physical Verification Status': 'physicalVerificationStatus',
  'Remarks\n(Document Side)': 'remarksDocumentSide',
  'Asigned Client Name': 'assignedClientName',
  'Asigned Client ID': 'assignedClientId',
  'Remarks\n(Client Side)': 'remarksClientSide',
  'Remarks\n(Over All)': 'remarksOverall',
  'Follow-up Date': 'followUpDate',
  'Created By': 'createdBy',
  'Last Updated On': 'lastUpdatedOn',
};

/** Recursively remaps Google-Sheets-style column names (with spaces) to camelCase keys. */
export function remapWorkerKeys(obj: unknown): unknown {
  if (Array.isArray(obj)) {
    return obj.map(remapWorkerKeys);
  }
  if (obj && typeof obj === "object") {
    const result: Record<string, unknown> = {};
    for (const key of Object.keys(obj as Record<string, unknown>)) {
      const mappedKey = workerKeyMapping[key] || key;
      result[mappedKey] = (obj as Record<string, unknown>)[key];
    }
    return result;
  }
  return obj;
}
